---
version: 2
updates:
    - package-ecosystem: gomod
      directory: /
      schedule:
          interval: daily
          time: 11:00
      open-pull-requests-limit: 10
      ignore:
          - dependency-name: github.com/pterm/pterm
          - dependency-name: github.com/spf13/cobra
