---
repos:
    - repo: https://github.com/adrienverge/yamllint.git
      rev: v1.34.0
      hooks:
          - id: yamllint

    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.3
      hooks:
          - id: yamlfmt

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: trailing-whitespace
          - id: check-added-large-files
          - id: check-case-conflict
          - id: check-merge-conflict
          - id: check-shebang-scripts-are-executable
          - id: check-symlinks
          - id: check-toml
          - id: check-yaml
          - id: check-json
          - id: detect-private-key
          - id: end-of-file-fixer
          - id: pretty-format-json
            args: [--autofix]

    - repo: https://github.com/jumanjihouse/pre-commit-hooks
      rev: 3.0.0
      hooks:
          - id: git-check
          - id: git-dirty
          - id: script-must-have-extension


    - repo: https://github.com/gruntwork-io/pre-commit
      rev: v0.1.23
      hooks:
          - id: shellcheck

    - repo: https://github.com/mineiros-io/pre-commit-hooks
      rev: v0.5.0
      hooks:
          - id: terraform-fmt
            files: ^test-data/terraform/.+\.tf$
          - id: terraform-validate
            files: ^test-data/terraform/.+\.tf$

    - repo: https://github.com/dnephin/pre-commit-golang
      rev: v0.5.1
      hooks:
          - id: go-fmt
            files: ^(pkg|cli|cmd)/(.*/)*.*\.go$
          - id: go-vet
            files: ^(pkg|cli|cmd)/(.*/)*.*\.go$
          - id: go-build
            files: ^(pkg|cli|cmd)/(.*/)*.*\.go$
          - id: go-mod-tidy
            files: ^(pkg|cli|cmd)/(.*/)*.*\.go$

    - repo: https://github.com/igorshubovych/markdownlint-cli
      rev: v0.39.0
      hooks:
          - id: markdownlint
            args: [--fix, .]

    - repo: https://github.com/tcort/markdown-link-check
      rev: v3.11.2
      hooks:
          - id: markdown-link-check
            args:
                - -q
                - --config=.markdown-link-check.json

    - repo: https://github.com/golangci/golangci-lint
      rev: v1.56.1
      hooks:
          - id: golangci-lint
            args: [--config, .golangci.yml]
