---
version: '3'
env:
    ENV: '{{.ENV}}'

vars:
    MODULE: '{{default "root-module-1" .MODULE}}'
    VARS: '{{default "" .VARS}}'
    BINARY: '{{default "cli" .BINARY}}'
    TERRAFORM_TESTS_MODULES_DIR: '{{default "test/terraform" .TERRAFORM_TESTS_MODULES_DIR}}'

dotenv: ['.env.{{.ENV}}.aws', '.env.{{.ENV}}.terraform', '.env.{{.ENV}}.terragrunt']

includes:
    common:
        taskfile: ./taskfiles/taskfile.common.yml
    precommit:
        taskfile: ./taskfiles/taskfile.precommit.yml
    tf:
        taskfile: ./taskfiles/Taskfile.terraform.yml
    golang:
        taskfile: ./taskfiles/Taskfile.go.yml
tasks:
    # ***********************
    # Common tasks
    # ***********************
    default:
        cmds:
            - task: common:default

    pc-init:
        desc: Initialize and install required hooks
        cmds:
            - task: precommit:hooks-init

    pc-run:
        desc: Run all the hooks described in the .pre-commit-config.yaml file
        cmds:
            - task: precommit:hooks-run
      # ****************************************************
      # Go Tasks
      # ****************************************************
    go-ci:
        desc: Execute all the go CI tasks in the pkg/root module.
        dir: cli
        cmds:
            - task: golang:go-tidy
            - task: golang:go-fmt
            - task: golang:go-vet
            - task: golang:go-lint
            - task: golang:go-test

    cli-build:
        desc: Build the terradagger CLi
        dir: ./cli
        sources:
            - ./main.go
        generates:
            - ./{{.BINARY}}
        cmds:
            - if [ -f ./{{.BINARY}} ]; then rm ./{{.BINARY}}; fi
            - go build -o {{.BINARY}} ./main.go
    cli-run:
        desc: Run the terradagger CLi
        dir: ./cli
        deps: [cli-build]
        cmds:
            - ./{{.BINARY}} {{.CLI_ARGS}}
    cli-run-src:
        desc: Run the terradagger CLi from source
        dir: ./cli
        cmds:
            - go run ./main.go {{.CLI_ARGS}}

    # ***********************
    # Terraform task (modules)
    # (These tasks are used to run terraform commands in the examples directory)
    # ***********************
    tf-init:
        desc: Initialize the terraform module
        cmds:
            - task: common:clean
            - task: tf:init
              vars: {TF_WORKING_DIR: '{{.TERRAFORM_TESTS_MODULES_DIR}}/{{.MODULE}}'}

    tf-plan:
        desc: In the terraform module, execute a terraform plan
        cmds:
            - task: common:clean
            - task: tf:init
              vars: {TF_WORKING_DIR: '{{.TERRAFORM_TESTS_MODULES_DIR}}/{{.MODULE}}'}
            - task: tf:plan
              vars: {TF_WORKING_DIR: '{{.TERRAFORM_TESTS_MODULES_DIR}}/{{.MODULE}}', TF_VARS_FILE: '{{.VARS}}'}

    tf-apply:
        desc: In the terraform module, execute a terraform apply
        cmds:
            - task: common:clean
            - task: tf:init
              vars: {TF_WORKING_DIR: '{{.TERRAFORM_TESTS_MODULES_DIR}}/{{.MODULE}}'}
            - task: tf:apply
              vars: {TF_WORKING_DIR: '{{.TERRAFORM_TESTS_MODULES_DIR}}/{{.MODULE}}', TF_VARS_FILE: '{{.VARS}}'}

    tf-destroy:
        desc: In the terraform module, execute a terraform destroy
        cmds:
            - task: common:clean
            - task: tf:init
              vars: {TF_WORKING_DIR: '{{.TERRAFORM_TESTS_MODULES_DIR}}/{{.MODULE}}'}
            - task: tf:destroy
              vars: {TF_WORKING_DIR: '{{.TERRAFORM_TESTS_MODULES_DIR}}/{{.MODULE}}', TF_VARS_FILE: '{{.VARS}}'}

    tf-ci:
        desc: Run CI tasks for the terraform modules as part of the 'test-data' directory
        cmds:
            - task: common:clean
            - task: tf:init
              vars: {TF_WORKING_DIR: '{{.TERRAFORM_TESTS_MODULES_DIR}}/{{.MODULE}}'}
            - task: tf:validate
              vars: {TF_WORKING_DIR: '{{.TERRAFORM_TESTS_MODULES_DIR}}/{{.MODULE}}'}
            - task: tf:fmt-fix
              vars: {TF_WORKING_DIR: '{{.TERRAFORM_TESTS_MODULES_DIR}}/{{.MODULE}}'}
            - task: tf:lint
              vars: {TF_WORKING_DIR: '{{.TERRAFORM_TESTS_MODULES_DIR}}/{{.MODULE}}'}
            - task: tf:docs
              vars: {TF_WORKING_DIR: '{{.TERRAFORM_TESTS_MODULES_DIR}}/{{.MODULE}}'}

    tf-docs:
        desc: Generate terraform docs
        cmds:
            - task: common:clean
            - task: tf:docs
              vars: {TF_WORKING_DIR: '{{.TERRAFORM_TESTS_MODULES_DIR}}/{{.MODULE}}'}

    tf-docs-all:
        desc: Generate terraform docs for a set of modules and/or recipes
        cmds:
            - task: common:clean
            - task: tf:doc-modules
              vars: {TF_MODULES_DIR: '{{.TERRAFORM_TESTS_MODULES_DIR}}'}
            - task: tf:doc-recipes
              vars: {TF_RECIPES_DIR: '{{.TERRAFORM_TESTS_MODULES_DIR}}'}
