---
name: Docker Build
on:
    workflow_dispatch:
    push:
    pull_request:
env:
    GO_VERSION: ~1.21
jobs:
    docker-build:
        name: Docker build
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
            matrix:
                dockerFile: [container/Dockerfile, container/arm.Dockerfile]
        steps:
            - uses: actions/checkout@v3
            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: ${{ env.GO_VERSION }}
            - name: Build docker
              run: make docker-build dockerfile_default=${{ matrix.dockerFile }}
