---
name: Terraform Check

on:
    push:
    pull_request:
        types: [opened, edited, synchronize]

env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_DEFAULT_REGION: us-east-1

jobs:
    CI-modules:
        name: CI - Modules
        strategy:
            fail-fast: false
            matrix:
                include:
                    - name: default
                      tf_version: 1.3.6

                    - name: stack-dns-zone-multi-account
                      tf_version: 1.3.6

        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: modules/${{ matrix.name }}
        steps:
            - uses: actions/checkout@v3
            - uses: hashicorp/setup-terraform@v1
              with:
                  terraform_version: ${{ matrix.tf_version }}
            - run: terraform init
            - run: terraform validate
            - run: terraform fmt -check=true

            - name: Terraform TFLintSetup
              id: terraform-tflint-setup
              uses: terraform-linters/setup-tflint@v1
              with:
                  tflint_version: latest

            - name: TFLint Run
              id: terraform-tflint-run
              run: |
                  tflint --version
                  tflint --init
                  tflint --disable-rule=terraform_module_pinned_source
                  tflint .

    CI-recipes:
        name: CI - Recipes
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                include:
                    - name: basic
                      module: default
                      tf_version: 1.3.6

                    - name: basic
                      module: stack-dns-zone-multi-account
                      tf_version: 1.3.6

        defaults:
            run:
                working-directory: examples/${{ matrix.module }}/${{ matrix.name }}

        needs: CI-modules
        steps:
            - uses: actions/checkout@v2
            - uses: hashicorp/setup-terraform@v1
              with:
                  terraform_version: ${{ matrix.tf_version }}
            - run: terraform init
            - run: terraform validate
            - run: terraform fmt -check=true

            - name: Terraform TFLintSetup
              id: terraform-tflint-setup
              uses: terraform-linters/setup-tflint@v1
              with:
                  tflint_version: latest

            - name: TFLint Run
              id: terraform-tflint-run
              run: |
                  tflint --version
                  tflint --init
                  tflint --disable-rule=terraform_module_pinned_source
                  tflint .
