---
name: Yaml Linter
on:
    workflow_dispatch:
    push:
    pull_request:
jobs:
    yamllint:
        name: Yamllint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Lint Workflows
              uses: karancode/yamllint-github-action@v2.1.1
              with:
                  yamllint_config_filepath: .yamllint.yml
                  yamllint_file_or_dir: .github/workflows
                  yamllint_comment: 'true'
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Lint GitHub config yamls
              uses: karancode/yamllint-github-action@v2.1.1
              with:
                  yamllint_config_filepath: .yamllint.yml
                  yamllint_file_or_dir: .github
                  yamllint_comment: 'true'
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Lint yaml files in root dir
              uses: karancode/yamllint-github-action@v2.1.1
              with:
                  yamllint_config_filepath: .yamllint.yml
                  yamllint_comment: 'true'
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
